version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-ecr: circleci/aws-ecr@7.3.0

executors:
  arm64-executor:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    resource_class: arm.medium

jobs:
  run_tests:
    executor: arm64-executor
    steps:
      - checkout
      - run:
          name: System information
          command: uname -a
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test

  build_and_push_image:
    executor: arm64-executor
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: $AWS_RESOURCE_NAME_PREFIX

workflows:
  build_test_push:
    jobs:
      - run_tests
      - build_and_push_image:
          requires:
            - run_tests
