version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1
  cloudformation: frameio/cloudformation@0.25.1

executors:
  arm64-executor:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
    resource_class: arm.medium

jobs:
  run_tests:
    executor: arm64-executor
    steps:
      - checkout
      - run:
          name: System information
          command: uname -a
      - run:
          name: Create package-lock.json
          command: npm install     
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test

  build_and_push_image:
    executor: arm64-executor
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: $AWS_RESOURCE_NAME_PREFIX
          tag: "${CIRCLE_SHA1},latest"

  update_service:
    executor: arm64-executor
    steps:
      - checkout
      - aws-cli/setup
      - aws-ecs/update-service:
          cluster-name: 'hippo-arm-cluster'
          service-name: 'hippo-arm-service'
          family: 'hippo-arm-task'
          container-image-name-updates: 'container=hippo-arm-container,tag=latest'
      - aws-ecs/run-task:
          assign-public-ip: ENABLED
          task-definition: 'hippo-arm-task-${CIRCLE_BUILD_NUM}'
          cluster: 'hippo-arm-cluster'
          subnet-ids: subnet-064e730a31ba6c0d5

workflows:
  setup_build_test_push_deploy:
    jobs:
      - cloudformation/lint:
          template: cf/fargate-hippo.yml
      - cloudformation/changeset:
          stack_name: hippo-arm-stack
          template: cf/fargate-hippo.yml
          args: --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
          requires:
            - cloudformation/lint
      - cloudformation/deploy:
          stack_name: hippo-arm-stack
          template: cf/fargate-hippo.yml
          args: --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
          requires:
            - cloudformation/changeset
      - run_tests:
          requires:
            - cloudformation/deploy
      - build_and_push_image:
          requires:
            - run_tests
      - update_service:
          requires:
            - build_and_push_image